apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpicola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpicola
  template:
    metadata:
      labels:
        app: alpicola
    spec:
      containers:
      - name: alpicola
        image: roskenet/alpicola:2.81.0
        ports:
        - name: www
          containerPort: 80
