replicaCount: 1

image:
  repository: bitnami/kafka
  tag: 3.8
  pullPolicy: IfNotPresent

kafka:
  nodeId: 0
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  listeners: PLAINTEXT://:9092,CONTROLLER://:9093
  advertisedListeners: PLAINTEXT://kafka:9092
  listenerSecurityProtocolMap: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  controllerQuorumVoters: 0@kafka:9093

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  hostPath:
    enabled: true
    basePath: /mnt
  volumes:
    - name: data
      mountPath: /var/lib/kafka/data
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      reclaimPolicy: Retain
    - name: secrets
      mountPath: /var/lib/kafka/secrets
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      reclaimPolicy: Retain
