apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    meta.helm.sh/release-name: ingress
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2025-08-08T07:47:34Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: petunia
  namespace: default
  resourceVersion: "1258740"
  uid: 6ec0a606-e66f-4ff7-8ab3-3485c89c1f26
spec:
  ingressClassName: nginx
  rules:
  - host: auth.roskenet.de
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: www.roskenet.de
    http:
      paths:
      - backend:
          service:
            name: polonium
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: petunia.roskenet.de
    http:
      paths:
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /ws
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /oauth2
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /login
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /logout
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /me
        pathType: Prefix
      - backend:
          service:
            name: alpicola
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www.roskenet.de
    - petunia.roskenet.de
    - auth.roskenet.de
    secretName: petunia-tls
status:
  loadBalancer:
    ingress:
    - ip: 217.154.117.238
