apiVersion: v1
kind: Secret
metadata:
  name: petunia-secrets
type: Opaque
stringData:
  KEYCLOAK_SECRET: miqtl8qIoEuLXXEOzvDmwP63xFWXaNje
  KEYCLOAK_ADMIN: keycloak
  KEYCLOAK_ADMIN_PASSWORD: keycloak
