apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
#    nginx.ingress.kubernetes.io/rewrite-target: /
  name: petunia
spec:
  ingressClassName: nginx
  rules:
  - host: keycloak.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 80
  - host: petunia.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: alpicola
              port:
                number: 80
        - path: /me
          pathType: Prefix
          backend:
            service:
              name: villadiana
              port:
                number: 80
        - path: /oauth2
          pathType: Prefix
          backend:
            service:
              name: villadiana
              port:
                number: 80
        - path: /logout
          pathType: Prefix
          backend:
            service:
              name: villadiana
              port:
                number: 80
        - path: /login
          pathType: Prefix
          backend:
            service:
              name: villadiana
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: villadiana
              port:
                number: 80
