apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: petunia
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: alpicola
    http:
      paths:
      - backend:
          service:
            name: alpicola
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: keycloak
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: polonium
    http:
      paths:
      - backend:
          service:
            name: polonium
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: villadiana
    http:
      paths:
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /ws
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /oauth2
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /login
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /logout
        pathType: Prefix
      - backend:
          service:
            name: villadiana
            port:
              number: 8080
        path: /me
        pathType: Prefix
