apiVersion: apps/v1
kind: Deployment
metadata:
  name: villadiana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: villadiana
  template:
    metadata:
      labels:
        app: villadiana
    spec:
      containers:
      - name: villadiana
        image: roskenet/villadiana:3.51.0
        ports:
        - name: www
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: villadiana
        env:
        - name: KEYCLOAK_VILLADIANA_SECRET
          valueFrom:
            secretKeyRef:
              name: petunia-secret
              key: KEYCLOAK_VILLADIANA_SECRET
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petunia-secret
              key: VALKEY_PASSWORD
