spring:
  profiles:
    active: ${ENVIRONMENT:local}
  application:
    name: bank
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JCBC_PASSWORD}
server:
  port: ${API_PORT:8080}
