apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
data:
  JDBC_URL: "jdbc:postgresql://postgres/keycloak"
  HOSTNAME: "https://auth.roskenet.de"
  KEYCLOAK_ADMIN: "keycloak"
  DB_VENDOR: "postgres"
  DB_ADDR: "postgres"
  DB_PORT: "5432"
  DB_USER: "keycloak"
  DB_DATABASE: "keycloak"
  KC_HOSTNAME: "https://auth.roskenet.de"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
