apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.5
          imagePullPolicy: "IfNotPresent"
          args:
            - "start-dev"
            - "--db-url=${JDBC_URL}"
            - "--db=${DB_VENDOR}"
            - "--db-username=${DB_USER}"
            - "--db-password=${DB_PASSWORD}"
          env:
            - name: JDBC_URL
              value: "jdbc:postgresql://postgres/keycloak"
            - name: HOSTNAME
              value: https://auth.roskenet.de
            - name: KEYCLOAK_ADMIN
              value: keycloak
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: keycloak
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgres"
            - name: DB_PORT
              value: 5432
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak
            - name: DB_DATABASE
              value: keycloak
            - name: KC_HOSTNAME
              value: https://auth.roskenet.de
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"

          ports:
            - name: service
              containerPort: 8080

