apiVersion: v1
kind: Secret
metadata:
  name: petunia-secret
type: Opaque
stringData:
  POSTGRES_MASTER_PASSWORD: postgres
  KEYCLOAK_ADMIN_PASSWORD: keycloak
  KEYCLOAK_DB_PASSWORD: keycloak
  KEYCLOAK_VILLADIANA_SECRET:
  VALKEY_PASSWORD: password
