spring:
  application:
    name: villadiana
  profiles:
    default: prod
  session:
    store-type: redis
    redis:
      namespace: petunia:session
    timeout: 30m
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: localhost
      password: ${VALKEY_PASSWORD}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            token-uri: ${KEYCLOAK_TOKEN_URI}
        registration:
          keycloak:
            client-id: villadiana
            client-secret: ${KEYCLOAK_VILLADIANA_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            provider: keycloak

app:
  security:
    allowed-origin-patterns:
      - http://alpicola
      - https://petunia.roskenet.de
    post-logout-redirect-uri: https://petunia.roskenet.de
    default-login-success-url: https://petunia.roskenet.de/petunias

#server:
#  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  otlp:
    metrics:
      export:
        enabled: off
