apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petunia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petunia.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{- range $i, $vol := .Values.persistence.volumes }}
        - name: {{ $vol.name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" (include "petunia.fullname" $) $vol.name | trunc 63 | trimSuffix "-" }}
        {{- end }}
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BITNAMI_DEBUG
              value: "no"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_NODE_ID
              value: "{{ .Values.kafka.nodeId }}"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "{{ .Values.kafka.processRoles }}"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "{{ .Values.kafka.controllerListenerNames }}"
            - name: KAFKA_CFG_LISTENERS
              value: "{{ .Values.kafka.listeners }}"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "{{ .Values.kafka.advertisedListeners }}"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "{{ .Values.kafka.listenerSecurityProtocolMap }}"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "{{ .Values.kafka.controllerQuorumVoters }}"
          volumeMounts:
            {{- range $i, $vol := .Values.persistence.volumes }}
            - mountPath: {{ $vol.mountPath }}
              name: {{ $vol.name }}
            {{- end }}
