apiVersion: v1
kind: Service
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "petunia.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: client
    - port: 9093
      targetPort: 9093
      name: controller
